---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: default
spec:
  # type: NodePort
  type: NodePort
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000