---
- name: Pull docker image
  hosts: all
  tasks:
          - name: Pull the image from dockerhub
            docker_image:
                  name: nagasrihith608/numberplatedetection 
                  source: pull

          - name: Write command after pulling image
            shell: 'echo "Finished pulling image"'

          - name: running container
            shell: docker run -it -d nagasrihith608/numberplatedetection /bin/bash
