---
- name: Deploying website with Kubernetes
  hosts: localhost
  remote_user: saiksk
  tasks:
    - name: create website deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', './k8s-deploy.yaml') | from_yaml }}"
        state: present
    - name: create website service
      kubernetes.core.k8s:
        definition: "{{ lookup('file', './k8s-service.yaml') | from_yaml }}" 
        state: present